# Methylation Toolkit
Teresa mentioned she wants to see presence/absence for the DNA methylation toolkit in the oyster at my next committee meeting. This is inpsired by a talk she saw about land slugs.

## 0. load libraries

In [2]:
library(tidyverse)
library(rtracklayer)

## 1. read csvs

In [3]:
gtf <- as.data.frame(import('/work/pi_sarah_gignouxwolfsohn_uml_edu/julia_mcdonough_student_uml_edu/ref_files/genome/GCF_053477285.1_ASM5347728v1_genomic.gtf'))
head(gtf)

  seqnames    start end   width strand source type       score phase
1 NC_136047.1 34876 71533 36658 +      Gnomon gene       NA    NA
2 NC_136047.1 34876 71533 36658 +      Gnomon transcript NA    NA
3 NC_136047.1 34876 35035   160 +      Gnomon exon       NA    NA
4 NC_136047.1 46195 46780   586 +      Gnomon exon       NA    NA
5 NC_136047.1 49378 50230   853 +      Gnomon exon       NA    NA
6 NC_136047.1 53798 53912   115 +      Gnomon exon       NA    NA
  gene_id      ⋯ exon_number protein_id anticodon inference note pseudo
1 LOC144621260 ⋯ NA          NA         NA        NA        NA   NA
2 LOC144621260 ⋯ NA          NA         NA        NA        NA   NA
3 LOC144621260 ⋯ 1           NA         NA        NA        NA   NA
4 LOC144621260 ⋯ 2           NA         NA        NA        NA   NA
5 LOC144621260 ⋯ 3           NA         NA        NA        NA   NA
6 LOC144621260 ⋯ 4           NA         NA        NA        NA   NA
  exception transl_except part partial
1 NA        NA            NA   NA
2 NA        NA            NA   NA
3 NA        NA            NA   NA
4 NA        NA            NA   NA
5 NA        NA            NA   NA
6 NA        NA            NA   NA

## 2. Find methlyation toolkit genes

want to make a plot with presence/absence of methylation toolkit - starting a df with this info

In [ ]:
df <- data.frame(
    gene = c('DNMT1', 'DNMT2', 'DNMT3',
             'TET1', 'TET2', 'TET3',
             'MBD1', 'MBD2', 'MBD3', 'MBD4', 'MECP2'),
    purpose = c('Writer', 'Writer', 'Writer',
                'Eraser', 'Eraser', 'Eraser',
                'Reader', 'Reader', 'Reader', 'Reader', 'Reader'),
    present = c('Present', 'Absent'))

head(df)

### writers of DNAme

#### DNMT1
LOC111121210

In [17]:
unique(gtf %>% filter(str_detect(description, "DNA methyltransferase"))%>% select(gene_id, description))

  gene_id      description
1 LOC111121210 DNA methyltransferase 1-associated protein 1-like

#### DNMT2
according to [Gavery and Roberts](https://link.springer.com/content/pdf/10.1186/1471-2164-11-483), a DNMT2 homolog has not been found (at least for *C. gigas*)

#### DNMT3

### erasers of DNAme

#### TET1
LOC111118472

In [6]:
unique(gtf %>% filter(str_detect(description, "TET1"))%>% select(gene_id, description))

  gene_id      description
1 LOC111118472 methylcytosine dioxygenase TET1-like

#### TET2

In [7]:
unique(gtf %>% filter(str_detect(description, "TET2"))%>% select(gene_id, description))

     gene_id description

#### TET3

In [9]:
unique(gtf %>% filter(str_detect(description, "TET3"))%>% select(gene_id, description))

     gene_id description

### readers

#### MBD1
also absent in land slug

#### MBD2
LOC111128560

In [14]:
unique(gtf %>% filter(str_detect(description, "methyl-CpG"))%>% select(gene_id, description))

  gene_id      description
1 LOC111107813 methyl-CpG-binding domain protein 4-like
2 LOC111128560 methyl-CpG-binding domain protein 2-like

#### MBD3
also absent in land slug

#### MBD4
LOC111107813

In [14]:
unique(gtf %>% filter(str_detect(description, "methyl-CpG"))%>% select(gene_id, description))

  gene_id      description
1 LOC111107813 methyl-CpG-binding domain protein 4-like
2 LOC111128560 methyl-CpG-binding domain protein 2-like

#### MECP2